version: "3.8"

services:
  test:
    image: johnnyhuy/actions-discord-git-webhook/test:latest
    entrypoint: /opt/workspace/node_modules/.bin/jest
    build:
      context: .
      dockerfile: action.Dockerfile
    volumes:
      - "./tests:/opt/workspace/tests"
