name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: make test

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        name: Set Git User
        with:
          global: false
          name: "George the Lilac Cat"
          email: "95064644+georgelilaccat@users.noreply.github.com"
          actor: "georgelilaccat"
          token: "${{ secrets.SERVICE_GITHUB_TOKEN }}"

      - name: Build
        run: make build

      - name: Version
        run: make version

      - name: Release
        run: make release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.SERVICE_GITHUB_TOKEN }}
