name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/install@v4

      - run: make install

      - run: make test

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: false
          name: George the Lilac Cat
          email: 95064644+georgelilaccat@users.noreply.github.com
          actor: georgelilaccat
          token: "${{ secrets.SERVICE_GITHUB_TOKEN }}"

      - run: make build

      - run: make version

      - run: make release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.SERVICE_GITHUB_TOKEN }}
