name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          docker compose -f compose.yaml build test
          docker compose -f compose.yaml run --rm test

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        name: Set Git User
        with:
          global: false
          name: "George the Lilac Cat"
          email: "95064644+georgelilaccat@users.noreply.github.com"
          actor: "georgelilaccat"
          token: "${{ secrets.SERVICE_GITHUB_TOKEN }}"

      - name: Build
        run: docker compose build release

      - name: Version
        run: docker compose run --rm release standard-version

      - name: Release
        run: |
          git push --follow-tags origin main
          docker compose run --rm release conventional-github-releaser
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.SERVICE_GITHUB_TOKEN }}
