name: Test

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        run: |
          docker compose -f compose.test.yaml build test
          docker compose -f compose.test.yaml run --rm test
